[project]
name = "bankofsam-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "plotly>=6.3.1",
    "streamlit>=1.51.0",
    "streamlit-autorefresh>=1.0.1",
    "streamlit-flow>=0.1.0",
]
